apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qnl05jr1z-python
  janus-idp.io/tekton: qnl05jr1z-python
  backstage.io/kubernetes-id: qnl05jr1z-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qnl05jr1z-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
